### ISSUE TITLE
Not working on multisite

### ISSUE THREAD

**Issue by opeus** [pcfreak30/wp-criticalcss#1]
I have your plugin installed on my multisite.

I have latest wordpress.

I’ve deactivated every other plugin.

I host at wpengine.

I’ve cleared all caches.

I’ve checked my api key.

I see that there are multisite settings when I go to mysites/network admin/plugins, however there are no settings/options when in the admin for the individual site. Is this correct?

Thanks,

Dan

**Comment by pcfreak30** [comment]
Please see my reply at https://wordpress.org/support/topic/not-working-on-multisite-16/#post-8970237
