### ISSUE TITLE
everything is "pending" - is that ok?

### ISSUE THREAD

**Issue by brunocrosier** [pcfreak30/wp-criticalcss#2]
hi! firstly thanks for contributing all this as opensource. awesome !

i've set everything up, and this is what i see. is this correct? is there any way to test whether it's working as supposed to? on criticalcss.com everything is showing up as having a yellow triangle

thanks 

![image](https://cloud.githubusercontent.com/assets/18399089/24528389/215a8d3c-159e-11e7-944e-0b4045e262c7.png)

![image](https://cloud.githubusercontent.com/assets/18399089/24528437/594ac784-159e-11e7-8d21-fd847370a3a0.png)

**Comment by pcfreak30** [comment]
Yes it only processes 1 item at a time. You can shake a fist at Jonas @ criticalcss.com for that as he requested the queue operate how it is now to not overload servers.

In the future please stick to WP forums for support and here for problems :).
