### ISSUE TITLE
Feature Request: "WP Critical CSS Cache" tab

### ISSUE THREAD

**Issue by graylaurenm** [pcfreak30/wp-criticalcss#4]
The "Queue" tab really confused me at first, so I think a "Cache" tab could improve user experience by acting as a feedback mechanism. This would show which URLs have been successfully processed by CriticalCSS.com and empties when cache is cleared.

**Comment by pcfreak30** [comment]
Thanks, this will be in the next major release. You can monitor progress in the beta and framework branches.

**Comment by pcfreak30** [comment]
This has been implemented.
