### ISSUE TITLE
Feature request: Force include (missing) styles

### ISSUE THREAD

**Issue by pocketjoso** [pcfreak30/wp-criticalcss#5]
I suggest to add a ~ `forceIncludeCssSelectors` option in the plugin, visible in the UI, to allow the user to enter strings or regexes to match css selectors, for which the criticalcss.com API will keep their styles in the critical css no matter what:
```js
forceIncludeCssSelectors: [
      '.keepMeEvenIfNotSeenOrNotDeemedCritical',
      /^\.regexWorksToo/
]
```

The use case for this is when the HTML (some part of it) is setup in a way that doesn't work for the critical css generation and it is not feasible to change it. For example, elements appearing early in the DOM but using absolute positioning to "hide" themselves outside of the critical viewport will not be considered critical by criticalcss.com, and the styles for the hiding will thus be missing. In this case the developer could force include the "hiding" styles for the element.

**Comment by pcfreak30** [comment]
This would require cooperation from Jonas to enable since the plugin is technically just an API client and I am not an employee or partner of criticalcss.com, only an affiliate.

**Comment by pocketjoso** [comment]
Jonas here. :) I can expose this in the API very quickly, it's already supported in the codebase of criticalcss.com.

**Comment by pcfreak30** [comment]
@pocketjoso wow sorry I was not aware of your github username :P.

**Comment by pocketjoso** [comment]
Getting asked for this again - is it on your TODO to add in the plugin?

**Comment by pcfreak30** [comment]
I can add it in but need you to clarify the request args to send.

**Comment by pcfreak30** [comment]
@pocketjoso im looking at this again now and need to know how you would differentiate from a string and regex.

**Comment by pocketjoso** [comment]
Indeed, they need to be annotated to be picked up. `forceInclude` supports this format:

```json
{"forceInclude": [
    {"type": "RegExp", "value": "#footer"},
    {"value": "not a regex"}
]}
```

**Comment by pcfreak30** [comment]
@pocketjoso would this support js regex modifiers. like `{"type": "RegExp", "value": "/#footer/i"},`?

**Comment by pocketjoso** [comment]
never thought about case insensitive - it's the only flag that makes sense for `forceInclude`.

I'll make this change, but note that this will be a breaking change (since it's not in use yet) - so you will no longer be able to pass just `#footer`, instead `value` will now have to be a valid (js) regex. Note as well that any `\` needs to be escaped inside your JSON payload, which you might or might not get automatically, depending on whether you will be operating on pure strings, or regexes.

So yes, final api will be:
```JSON
{"type": "RegExp", "value": "/#footer/i"}
```
Where `value` is a valid JS regex, in string format, with any `\` occurance escaped (as `\\`).

**Comment by pocketjoso** [comment]
Live now, in production.

**Comment by pcfreak30** [comment]
@pocketjoso A question comes to mind. Can the regex delimiter only be a forward slash? And how can the regex be validated if there's errors I can test with preg_match on php but I think theres some subtle differences in the regex engines. Trying to ensure this is idot proof even for super advanced users so no debugging/guess work is needed.

**Comment by pocketjoso** [comment]
@pcfreak30 
> Can the regex delimiter only be a forward slash

Yes, that is what the API supports now. We could also have split up and passed in `pattern` and `flags` separately instead of a combined `value`, but I went with the former now.

Regarding validation - first of all, if the regex is invalid it will just be ignored, so it will not break anything. Currently the API does not surface any warning about this back to you however. For you to validate it yourself is fairly trivial - this is the validation regex I use, in JS: `/^\/.*?\/[gimy]*$/`.

Finally note that the forceInclude list is tested towards on individual selector parts of css rules, i.e. in the rule:
```css
body, main,
.button,
.button:hover > .content {}
```
It would be tested towards, in turn:
`body`
`main`
`.button`
`.button:hover > .content`

-> hence what I mean to show here is that there should not be much use for very complicated regexes - since they will always just be tested towards a single line of text.

**Comment by pcfreak30** [comment]
@pocketjoso i tried that regex but it seemed to match `/ggggg/g/` too which is not right.

Currently i have `if ( '/' === $line[0] && '/' === $line[ strlen( $line ) - 1 ] && ! preg_match( '/^\/.*?\/[gimy]*$/', $line ) ) {` which checks for a regex by the 1st and last character and then see if it matches the regex regex.

**Comment by pocketjoso** [comment]
Well, indeed I would only extract the valid first part out of the example you gave, omitting the final slash. If you want to make sure that the whole string is a valid regex without any extra characters then something like your extra checks would makes sense.

However for me it would make more sense for your UI to only ask for the pattern (what goes between the `//`), and then just have a checkbox for `case sensitive` (i.e. `i`). This way you don't need any validation, and users are less confused about `g` etc flags that don't have any effect anyway. (I mean that you would then yourself construct the regex (string) from pattern + flags)

**Comment by pcfreak30** [comment]
This has been implemented
