### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by paoloeuvrard** [pcfreak30/wp-criticalcss#6]
Hi,

I bought an API and the plugin is working on it since yesterday, but It still hasn't changed anything at http://www.paolowebdesign.com

Is there something I missed?

Should I keep the window open for the plugin to work, maybe?

Thanks,
Paolo
PS: I am not in a hurry though, if it takes longer, no problem.

**Comment by pcfreak30** [comment]
Hello, please use forums for support. There also may be some bugs until the next release which should be very soon. Also good to know if you are using any caching plugin.

Thanks!.

**Comment by paoloeuvrard** [comment]
I am using WP_Rocket as recommended. Which forum addresses the issues?

**Comment by pcfreak30** [comment]
https://wordpress.org/support/plugin/wp-criticalcss. Also in this case as stated please wait for next release and if its still broke I can assist.
