### ISSUE TITLE
There is no way to purge critical CSS for a page.

### ISSUE THREAD

**Issue by incraigulous** [pcfreak30/wp-criticalcss#8]
Criticalcss.com is picking up some old CSS from the inlined styles even though my CSS files have changed. How can I purge all the critical CSS from the database (or from an individual page) and start over?

**Comment by pcfreak30** [comment]
Are you using the template mode or normal page mode?

**Comment by incraigulous** [comment]
Normal page mode.

**Comment by pcfreak30** [comment]
Click the checkbox `Force a web check on all pages for css changes. This will run for new web requests.` to reset the css. It does not clear out the CSS immediately, but will have it reprocess the next page request (assuming no cache or on a supported cache plugin/host).

It will store as meta `wp_criticalcss_ccss_cache` for post, term and user meta, and transients for any other URL.

**Comment by incraigulous** [comment]
OK, thanks! I ended up just deleting the criticalcss rows for that page out in the meta table. I suppose that's easy enough.
